### ISSUE TITLE
[PE-D][Tester E] AddAppointment issues

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-1/tp#229]
Despite 2 occurrences of the name: "bernice" in the database, adding appointment for patients with names containing "bernice" is not allowed. Perhaps it can be specified in either the command display or output that a strict name match should be present.

![image.png](https://raw.githubusercontent.com/nehcuy/ped/main/files/4ffae62c-4a0b-491e-9ac5-39178b6dc3f3.png)

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: nehcuy/ped#5

**Comment by guokweijie** [comment]
@TZL0 can add in UG for this limitation
