### ISSUE TITLE
[PE-D][Tester A] Undo/Redo commands do not have memory of selected entity

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-1/tp#242]
The Undo/Redo command does not remember the selected patient/appointment. 

**Steps to Reproduce**: 
- Start with the default data. 
- Add an appointment with Alex Yeoh: `aa n/Alex Yeoh t/X-Ray s/2022-12-12 12:00 d/Dr Tan`. 
- Select the patient `Alex Yeoh`: `slp 1`. Two appointments are shown now (one was already present in initial data). 

![Screenshot_20221028_175228.png](https://raw.githubusercontent.com/RezwanArefin01/ped/main/files/82fe250a-34c8-4c60-a886-34e9c982400e.png)

- Remove the first appointment: `da 1`. UI now shows one appointment. 

![Screenshot_20221028_175250.png](https://raw.githubusercontent.com/RezwanArefin01/ped/main/files/b21c3ab0-508d-413a-8433-cec8b95ed632.png)

- Undo: `undo`. 
    - **Expected**: The deleted appointment comes back. 
    - **Actual**: Same as Expected. 

![Screenshot_20221028_175309.png](https://raw.githubusercontent.com/RezwanArefin01/ped/main/files/632d5904-f6b7-4c5d-a1a9-4d30774e8e9d.png)

- Redo: `redo`. 
    - **Expected**: The appointment gets deleted and an empty list of appointments is shown.
    - **Actual**: The appointment gets deleted *but* UI shows all other appointments. Eg. the redo command is memory less. It does not remember that the program selected `Alex Yeoh`.

![Screenshot_20221028_175327.png](https://raw.githubusercontent.com/RezwanArefin01/ped/main/files/55d13df6-0d8f-4070-b1ad-dd66580dc2df.png)

This issue can be considers both a FeatureFlaw and a FunctionalityBug. Because in a sense, the Undo command is undoing both the delete *and* the select operations, where it is supposed to undo only 1 operation.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: RezwanArefin01/ped#10

**Comment by SpecOps2016** [comment]
fixed. will update as pr
