### ISSUE TITLE
[PE-D][Tester A] Inconsistent command format for targeting a patient

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S1-CS2103T-W08-1/tp#245]
Some command take name of a patient in the system, while some other takes the index. For example: 
- `editpatient INDEX ...` 
- `deletepatient INDEX ...`
- `addappointment n/NAME` 

It might be better to use one of the formats consistently. 

-------------
Labels: `severity.Low` `type.FeatureFlaw`
original: RezwanArefin01/ped#13

**Comment by guokweijie** [comment]
subjective, can ignore
