### ISSUE TITLE
[PE-D][Tester A] Data file is extremely hard to edit

### ISSUE THREAD

**Issue by nus-pe-script** [AY2223S1-CS2103T-W08-1/tp#247]
The data file has a very *flat* structure. It stores all patients, appointments, bills flatly, i.e. not nested.

For example: 
```json
{
  "patients" : [ {
    "name" : "Bernice Yu",
    "phone" : "99272758",
    "email" : "berniceyu@example.com",
    "address" : "Blk 30 Lorong 3 Serangoon Gardens, #07-18",
    "remark" : "",
    "tagged" : [ "colleagues", "friends" ]
  } ],
  "appointments" : [ {
    "name" : "Bernice Yu",
    "medicalTest" : "X-Ray",
    "slot" : "2022-09-15 11:00",
    "doctor" : "Dr Lim"
  } ], 
  "bills" : [ {
    "name" : "Bernice Yu",
    "slot" : "2022-09-15 11:00",
    "medicalTest" : "X-Ray",
    "doctor" : "Dr Lim",
    "billDate" : "2020-12-12",
    "amount" : "100.00",
    "paymentStatus" : "UNPAID"
  } ] 
}
```
The problem is: same information is repeated *many many* times. If someone wants to edit any of these fields, he has to find all occurrences of that field!

The problem is much more severe in case of appointment and bills. Here *all* the information in appointment is copied over to bill to establish the association. 

A much better design is to nest the classes, such as: 
```json
{
  "patients" : [ {
    "name" : "Bernice Yu",
    "phone" : "99272758",
    "email" : "berniceyu@example.com",
    "address" : "Blk 30 Lorong 3 Serangoon Gardens, #07-18",
    "remark" : "",
    "tagged" : [ "colleagues", "friends" ]
    "appointments": [ {
      "medicalTest" : "X-Ray",
      "slot" : "2022-09-15 11:00",
      "doctor" : "Dr Lim"
      "bills": [ {
        "billDate" : "2020-12-12",
        "amount" : "100.00",
        "paymentStatus" : "UNPAID"
      } ]
    } ]
  } ]
}
```
In this structure, one piece of information only exists in one place. 

This is marked as FeatureFlaw due to "Constraint-Human-Editable-File". The current design makes it much harder to achieve that. Though one might argue that editing the file is not considered "normal use". 

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: RezwanArefin01/ped#15

**Comment by guokweijie** [comment]
![image](https://user-images.githubusercontent.com/66172460/199158899-b9fbf391-3454-46c4-9ee3-f99df0ed8301.png)
